# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5518399a29d518e4e55b44d66d59b80d83e850d37c262e44103fda115455f5d3cfd968431c25d2e067db74886200ab32a0e7595e605e5aeabef7c804da26b194

test:
  secret_key_base: 5498b765b37056647be74462160e5b5d4a9f9a3b46c36c476772e0ce50f6acefb0fe244a6d0a0aed88fe35c45c8070d8332572688836aa577c69ef3e0ea25589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
